version: "3.8"
name: postgres-vector

services:
    db:
        image: pgvector/pgvector:pg17
        ports: 
            - ${DB_PORT}:5432
        environment:
            - POSTGRES_DB=${DB_NAME}
            - POSTGRES_PASSWORD=${DB_PASSWORD}
            - POSTGRES_USER=${DB_USER}
        container_name: postgres-with-pgvector
